### ISSUE TITLE
Can I run this on macOS ?

### ISSUE THREAD

**Issue by leovarmak** [Eroica-cpp/dota2scripts#1]

**Comment by Eroica-cpp** [comment]
Nope. It only supports Windows.

**Comment by leovarmak** [comment]
If possible make it available for macOS too. I get some main error while I try to run on macOS

**Comment by Eroica-cpp** [comment]
I'd like to make them available on macOS and Linux as well. I really do because I write code in linux while have to switch to windows to test and play, which is inconvenient.

But for now, it seems there's a long way to go.

**Comment by leovarmak** [comment]
Thanks a lot man. 
Just for reference here is the error I get

![image](https://user-images.githubusercontent.com/14135553/27315496-9746e8cc-5597-11e7-87a7-fbd1183a013e.png)
