### ISSUE TITLE
pls guide how to use script

### ISSUE THREAD

**Issue by realrj** [Eroica-cpp/dota2scripts#3]
There are many users like me so pls just give a brief introduction about how to use this lua script in game.
thanks

**Comment by Eroica-cpp** [comment]
1. Download a client from https://hake.me/

2. Put these files to the "./scripts" folder.

3. Run the client.

**Comment by realrj** [comment]
nothing free sir its paid

**Comment by Eroica-cpp** [comment]
Yea, it's a sad truth and I paid it too. I hope that I can develop a completely free, open source, and Linux-based scripting system someday.
