### ISSUE TITLE
Problem with Invoker.lua.

### ISSUE THREAD

**Issue by aleksonspore** [Eroica-cpp/dota2scripts#4]
Hi, Tao Li!
InstanceHelper in your scripts doesn't work correctly. If health is not full or while you moving, script doesn't switch to WWW(QQQ), but switch to last casted spell(if you cast Tornado and click moving - script switch to QWW).
thx, sorry for my bad english.

**Comment by Eroica-cpp** [comment]
I've updated the script. Does it work for you now?
